export type SprintBClusterDefinition = {
  slug: string;
  label: string;
  audience: "consumer" | "business" | "both";
  businessGoal: string;
  primaryIntent: string[];
  priorityQuestions: string[];
  commercialAngles: string[];
  hubPaths: string[];
  linkingRules: string[];
  coreCalculators: string[];
  coreArticles: string[];
  supportPages: string[];
};

export type SprintBRoadmapPage = {
  cluster: string;
  kind: "hub" | "calculator" | "article";
  slug: string;
  title: string;
  priorityTier: "tier-1" | "tier-2" | "tier-3";
  intent: string;
  reason: string;
};

export const SPRINT_B_CLUSTERS: SprintBClusterDefinition[] = [
  {
    slug: "credite-si-economii",
    label: "Credite și economii",
    audience: "consumer",
    businessGoal: "Captăm intenție mare de decizie financiară și pregătim suprafață bună pentru CTA-uri comerciale prudente.",
    primaryIntent: [
      "cost total credit",
      "rata maximă suportabilă",
      "refinanțare",
      "fond de urgență",
      "obiectiv de economisire",
    ],
    priorityQuestions: [
      "Ce rată lunară îmi permit fără să fragilizez bugetul?",
      "Cât costă total creditul, nu doar cât este rata lunară?",
      "Când merită refinanțarea și când doar mut costul?",
      "În cât timp ajung la avans sau la fondul de urgență?",
    ],
    commercialAngles: [
      "Credit nou versus refinanțare",
      "Lichiditate lunară versus cost total",
      "Economisire disciplinată versus obiectiv mare",
    ],
    hubPaths: ["/calculatoare/credite-si-economii", "/pentru-persoane"],
    linkingRules: [
      "Fiecare articol trimite către un calculator principal și un calculator de verificare.",
      "Hub-ul leagă întrebarea principală de un bloc answer-first, apoi de comparații între scenarii.",
      "Calculatoarele de credit trebuie să se citeze între ele prin cost total, rată și buffer de risc.",
    ],
    coreCalculators: [
      "calculator-cost-total-credit",
      "calculator-rata-maxima-suportabila",
      "calculator-economie-refinantare",
      "calculator-grad-de-indatorare",
      "calculator-fond-de-urgenta",
      "calculator-termen-obiectiv-economisire",
      "calculator-avans-locuinta",
      "calculator-economii-cu-dobanda",
      "calculator-pensie-suplimentara",
      "calculator-leasing-vs-credit",
    ],
    coreArticles: [
      "cum-citesti-costul-total-al-unui-credit",
      "cum-afli-ce-rata-iti-permiti-fara-sa-iti-blochezi-bugetul",
      "cand-merita-refinantarea-si-cand-doar-pare-o-idee-buna",
      "cum-iti-construiesti-fondul-de-urgenta-fara-sa-ramai-fara-lichiditati",
      "cum-planifici-economii-pe-termen-lung-pentru-obiective-mari",
      "leasing-vs-credit-cum-compari-corect-doua-scenarii-de-finantare",
    ],
    supportPages: [
      "/calculatoare/credite-si-economii",
      "/pentru-persoane",
      "/blog/cum-citesti-costul-total-al-unui-credit",
    ],
  },
  {
    slug: "energie-pentru-casa",
    label: "Energie pentru casă",
    audience: "consumer",
    businessGoal: "Construim clusterul cu cea mai bună combinație între intenție informațională, comparații de achiziție și monetizare prin echipamente.",
    primaryIntent: [
      "factura curent",
      "consum aparat",
      "panouri fotovoltaice",
      "amortizare fotovoltaice",
      "dimensionare climatizare/încălzire",
    ],
    priorityQuestions: [
      "Cât mă costă realist consumul de curent al casei?",
      "Câte panouri îmi trebuie pentru consumul actual?",
      "În cât timp se amortizează investiția în fotovoltaice?",
      "Ce putere de răcire sau încălzire are sens pentru locuința mea?",
    ],
    commercialAngles: [
      "Factura curentă versus economie potențială",
      "Investiție în panouri versus amortizare prudentă",
      "Alegerea echipamentului după cost anual, nu doar după putere",
    ],
    hubPaths: ["/calculatoare/energie-pentru-casa", "/pentru-persoane"],
    linkingRules: [
      "Articolele de explicare a facturii trebuie să trimită către factură, consum aparat și producție fotovoltaică.",
      "Calculatoarele fotovoltaice trebuie legate între ele în ordinea consum -> sistem -> producție -> amortizare.",
      "Hub-ul trebuie să separe clar zona de cost, zona de producție și zona de alegere echipament.",
    ],
    coreCalculators: [
      "calculator-factura-curent",
      "calculator-consum-aparat-electric",
      "calculator-necesar-sistem-fotovoltaic",
      "calculator-amortizare-panouri-fotovoltaice",
      "calculator-numar-panouri-fotovoltaice",
      "calculator-productie-fotovoltaica",
      "calculator-dimensiune-baterie-fotovoltaice",
      "calculator-necesar-incalzire",
      "calculator-dimensiune-pompa-de-caldura",
      "calculator-btu-aer-conditionat",
    ],
    coreArticles: [
      "cum-citesti-factura-de-curent-fara-sa-te-pierzi-in-detalii-inutile",
      "cum-citesti-amortizarea-unui-sistem-fotovoltaic",
      "cate-panouri-fotovoltaice-iti-trebuie-de-fapt",
      "cum-estimezi-productia-fotovoltaica-fara-promisiuni-umflate",
      "centrala-vs-pompa-de-caldura-cum-compari-corect-costurile",
    ],
    supportPages: [
      "/calculatoare/energie-pentru-casa",
      "/pentru-persoane",
      "/blog/cum-citesti-factura-de-curent-fara-sa-te-pierzi-in-detalii-inutile",
    ],
  },
  {
    slug: "imobiliare",
    label: "Imobiliare",
    audience: "consumer",
    businessGoal: "Facem hub-ul de decizie imobiliară util atât pentru locuire, cât și pentru investiții mici, cu pagini care pot monetiza prin lead-uri și comparații.",
    primaryIntent: [
      "cost total achiziție locuință",
      "preț pe mp",
      "chirie versus cumpărare",
      "randament din chirie",
      "costuri recurente proprietate",
    ],
    priorityQuestions: [
      "Cât mă costă cu adevărat achiziția, nu doar prețul de listă?",
      "Merită chirie sau cumpărare în scenariul meu actual?",
      "Ce randament rămâne după costurile reale?",
      "Cât de sensibilă este investiția la neocupare și renovare?",
    ],
    commercialAngles: [
      "Preț pe mp versus cost total de intrare",
      "Locuire proprie versus investiție mică",
      "Randament brut versus randament rămas după costuri",
    ],
    hubPaths: ["/calculatoare/imobiliare", "/pentru-persoane"],
    linkingRules: [
      "Pagina de cost total trebuie să trimită spre preț pe mp și buget lunar.",
      "Zona de investiție trebuie legată prin randament, neocupare, costuri recurente și administrare.",
      "Articolele chirie versus cumpărare trebuie să trimită spre două calculatoare complementare, nu doar unul.",
    ],
    coreCalculators: [
      "calculator-cost-total-achizitie-locuinta",
      "calculator-pret-pe-mp",
      "calculator-chirie-vs-cumparare",
      "calculator-buget-lunar-locuinta",
      "calculator-randament-chirie",
      "calculator-pierdere-din-neocupare",
      "calculator-buget-renovare",
      "calculator-avans-proprietate",
      "calculator-costuri-recurente-proprietate",
      "calculator-cost-administrare-proprietate",
    ],
    coreArticles: [
      "ce-intra-de-fapt-in-bugetul-total-de-achizitie-al-unei-locuinte",
      "chirie-vs-cumparare-cum-compari-corect-doua-scenarii",
      "cum-citesti-randamentul-din-chirie-fara-sa-ignori-costurile-ascunse",
      "cum-estimezi-un-buget-de-renovare-fara-optimism-periculos",
      "cat-te-costa-administrarea-unei-proprietati-inchiriate",
    ],
    supportPages: [
      "/calculatoare/imobiliare",
      "/pentru-persoane",
      "/blog/ce-intra-de-fapt-in-bugetul-total-de-achizitie-al-unei-locuinte",
    ],
  },
];

export const SPRINT_B_30_PAGE_ROADMAP: SprintBRoadmapPage[] = [
  {
    cluster: "credite-si-economii",
    kind: "hub",
    slug: "credite-si-economii",
    title: "Hub credite și economii",
    priorityTier: "tier-1",
    intent: "Hub principal pentru intenție financiară mare",
    reason: "Leagă cele mai bune pagini de credit, refinanțare și economisire într-o navigare clară.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-cost-total-credit",
    title: "Calculator cost total credit",
    priorityTier: "tier-1",
    intent: "Answer-first pentru cost total",
    reason: "E una dintre cele mai puternice pagini pentru decizie și monetizare.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-rata-maxima-suportabila",
    title: "Calculator rată maximă suportabilă",
    priorityTier: "tier-1",
    intent: "Buget lunar și stres financiar",
    reason: "Completează costul total și face clusterul mult mai acționabil.",
  },
  {
    cluster: "credite-si-economii",
    kind: "article",
    slug: "cum-citesti-costul-total-al-unui-credit",
    title: "Cum citești costul total al unui credit",
    priorityTier: "tier-1",
    intent: "Explicare și AEO",
    reason: "Ridică încrederea și susține calculatorul principal.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-economie-refinantare",
    title: "Calculator economie refinanțare",
    priorityTier: "tier-1",
    intent: "Comparație de scenarii",
    reason: "Are intenție comercială bună și leagă organic de oferte.",
  },
  {
    cluster: "credite-si-economii",
    kind: "article",
    slug: "cand-merita-refinantarea-si-cand-doar-pare-o-idee-buna",
    title: "Când merită refinanțarea",
    priorityTier: "tier-1",
    intent: "Decizie prudentă",
    reason: "Reduce riscul de conținut generic și crește E-E-A-T.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-grad-de-indatorare",
    title: "Calculator grad de îndatorare",
    priorityTier: "tier-2",
    intent: "Filtru de eligibilitate",
    reason: "Completează foarte bine rata maximă suportabilă.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-fond-de-urgenta",
    title: "Calculator fond de urgență",
    priorityTier: "tier-2",
    intent: "Obiectiv de economisire",
    reason: "Deschide clusterul spre disciplinarea financiară și CTA-uri soft.",
  },
  {
    cluster: "credite-si-economii",
    kind: "article",
    slug: "cum-iti-construiesti-fondul-de-urgenta-fara-sa-ramai-fara-lichiditati",
    title: "Cum îți construiești fondul de urgență",
    priorityTier: "tier-2",
    intent: "Educație financiară aplicată",
    reason: "Leagă creditele de lichiditate și buffer personal.",
  },
  {
    cluster: "credite-si-economii",
    kind: "article",
    slug: "cum-planifici-economii-pe-termen-lung-pentru-obiective-mari",
    title: "Cum planifici economii pe termen lung",
    priorityTier: "tier-3",
    intent: "Suport pentru economisire",
    reason: "Consolidează clusterul și deschide subtopicuri noi.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "hub",
    slug: "energie-pentru-casa",
    title: "Hub energie pentru casă",
    priorityTier: "tier-1",
    intent: "Hub principal pentru cost și echipamente",
    reason: "Este poarta de intrare pentru un cluster foarte bun de trafic și monetizare.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-factura-curent",
    title: "Calculator factură curent",
    priorityTier: "tier-1",
    intent: "Cost lunar realist",
    reason: "Are intenție simplă, volum bun și onboarding clar în cluster.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "article",
    slug: "cum-citesti-factura-de-curent-fara-sa-te-pierzi-in-detalii-inutile",
    title: "Cum citești factura de curent",
    priorityTier: "tier-1",
    intent: "Interpretare answer-first",
    reason: "Crește încrederea și reduce abandonul după prima cifră.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-consum-aparat-electric",
    title: "Calculator consum aparat electric",
    priorityTier: "tier-1",
    intent: "Cost punctual pe aparat",
    reason: "Este cea mai bună punte între interes vag și decizie practică.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-necesar-sistem-fotovoltaic",
    title: "Calculator necesar sistem fotovoltaic",
    priorityTier: "tier-1",
    intent: "Dimensionare investiție",
    reason: "Deschide tot clusterul fotovoltaic și comparațiile comerciale.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-amortizare-panouri-fotovoltaice",
    title: "Calculator amortizare panouri fotovoltaice",
    priorityTier: "tier-1",
    intent: "Payback și decizie financiară",
    reason: "Leagă costul energiei de decizia de investiție.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "article",
    slug: "cum-citesti-amortizarea-unui-sistem-fotovoltaic",
    title: "Cum citești amortizarea unui sistem fotovoltaic",
    priorityTier: "tier-1",
    intent: "Explicare și comparație",
    reason: "Previne concluziile naive și susține monetizarea prudentă.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "article",
    slug: "cate-panouri-fotovoltaice-iti-trebuie-de-fapt",
    title: "Câte panouri fotovoltaice îți trebuie",
    priorityTier: "tier-2",
    intent: "Sizing answer-first",
    reason: "Consolidează traseul consum -> sistem -> amortizare.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-productie-fotovoltaica",
    title: "Calculator producție fotovoltaică",
    priorityTier: "tier-2",
    intent: "Validare producție",
    reason: "Ajută mult la interpretarea amortizării și a numărului de panouri.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "article",
    slug: "centrala-vs-pompa-de-caldura-cum-compari-corect-costurile",
    title: "Centrală vs pompă de căldură",
    priorityTier: "tier-3",
    intent: "Comparație comercială",
    reason: "Deschide verticala de echipamente și oferte.",
  },
  {
    cluster: "imobiliare",
    kind: "hub",
    slug: "imobiliare",
    title: "Hub imobiliare",
    priorityTier: "tier-1",
    intent: "Hub pentru locuire și investiții mici",
    reason: "Poate deveni una dintre cele mai valoroase pagini de cluster.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-cost-total-achizitie-locuinta",
    title: "Calculator cost total achiziție locuință",
    priorityTier: "tier-1",
    intent: "Cost complet de intrare",
    reason: "Este cea mai importantă pagină de decizie pentru acest cluster.",
  },
  {
    cluster: "imobiliare",
    kind: "article",
    slug: "ce-intra-de-fapt-in-bugetul-total-de-achizitie-al-unei-locuinte",
    title: "Ce intră în bugetul total de achiziție",
    priorityTier: "tier-1",
    intent: "Interpretare și educație",
    reason: "Susține direct calculatorul principal și crește încrederea.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-pret-pe-mp",
    title: "Calculator preț pe mp",
    priorityTier: "tier-1",
    intent: "Comparație rapidă între oferte",
    reason: "E foarte bun pentru trafic și pentru intrarea în cluster.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-chirie-vs-cumparare",
    title: "Calculator chirie vs cumpărare",
    priorityTier: "tier-1",
    intent: "Comparație de scenarii",
    reason: "Are intenție mare și valoare foarte bună pentru sharing.",
  },
  {
    cluster: "imobiliare",
    kind: "article",
    slug: "chirie-vs-cumparare-cum-compari-corect-doua-scenarii",
    title: "Chirie vs cumpărare",
    priorityTier: "tier-1",
    intent: "Comparație answer-first",
    reason: "Poate lua snippet-uri și susține calculatorul principal.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-randament-chirie",
    title: "Calculator randament chirie",
    priorityTier: "tier-2",
    intent: "Investiție imobiliară mică",
    reason: "Deschide foarte bine subclusterul de randament.",
  },
  {
    cluster: "imobiliare",
    kind: "article",
    slug: "cum-citesti-randamentul-din-chirie-fara-sa-ignori-costurile-ascunse",
    title: "Cum citești randamentul din chirie",
    priorityTier: "tier-2",
    intent: "Interpretare randament",
    reason: "Previne concluzii greșite și crește E-E-A-T.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-buget-renovare",
    title: "Calculator buget renovare",
    priorityTier: "tier-2",
    intent: "Cost de adaptare sau investiție",
    reason: "Face clusterul mai complet pentru achiziție și investiție.",
  },
  {
    cluster: "imobiliare",
    kind: "article",
    slug: "cum-estimezi-un-buget-de-renovare-fara-optimism-periculos",
    title: "Cum estimezi un buget de renovare",
    priorityTier: "tier-3",
    intent: "Suport pentru decizie",
    reason: "Leagă costurile inițiale de scenariile reale.",
  },
];

export const SPRINT_B_GLOBAL_GAPS = [
  {
    slug: "zile-libere-2026",
    title: "Zile libere 2026",
    kind: "article" as const,
    reason: "Este singurul content gap real repetat în 404-uri și poate aduce trafic sezonier rapid.",
  },
];

export const getSprintBCluster = (slug: string) =>
  SPRINT_B_CLUSTERS.find((cluster) => cluster.slug === slug);
