export type SprintBClusterDefinition = {
  slug: string;
  label: string;
  audience: "consumer" | "business" | "both";
  businessGoal: string;
  primaryIntent: string[];
  priorityQuestions: string[];
  commercialAngles: string[];
  hubPaths: string[];
  linkingRules: string[];
  coreCalculators: string[];
  coreArticles: string[];
  supportPages: string[];
};

export type SprintBRoadmapPage = {
  cluster: string;
  kind: "hub" | "calculator" | "article";
  slug: string;
  title: string;
  priorityTier: "tier-1" | "tier-2" | "tier-3";
  intent: string;
  reason: string;
};

export const SPRINT_B_CLUSTERS: SprintBClusterDefinition[] = [
  {
    slug: "credite-si-economii",
    label: "Credite si economii",
    audience: "consumer",
    businessGoal: "Captam intentie mare de decizie financiara si pregatim suprafata buna pentru CTA-uri comerciale prudente.",
    primaryIntent: [
      "cost total credit",
      "rata maxima suportabila",
      "refinantare",
      "fond de urgenta",
      "obiectiv de economisire",
    ],
    priorityQuestions: [
      "Ce rata lunara imi permit fara sa fragilizez bugetul?",
      "Cat costa total creditul, nu doar cat este rata lunara?",
      "Cand merita refinantarea si cand doar mut costul?",
      "In cat timp ajung la avans sau la fondul de urgenta?",
    ],
    commercialAngles: [
      "Credit nou versus refinantare",
      "Lichiditate lunara versus cost total",
      "Economisire disciplinata versus obiectiv mare",
    ],
    hubPaths: ["/calculatoare/credite-si-economii", "/pentru-persoane"],
    linkingRules: [
      "Fiecare articol trimite catre un calculator principal si un calculator de verificare.",
      "Hub-ul leaga intrebarea principala de un bloc answer-first, apoi de comparatii intre scenarii.",
      "Calculatoarele de credit trebuie sa se citeze intre ele prin cost total, rata si buffer de risc.",
    ],
    coreCalculators: [
      "calculator-cost-total-credit",
      "calculator-rata-maxima-suportabila",
      "calculator-economie-refinantare",
      "calculator-grad-de-indatorare",
      "calculator-fond-de-urgenta",
      "calculator-termen-obiectiv-economisire",
      "calculator-avans-locuinta",
      "calculator-economii-cu-dobanda",
      "calculator-pensie-suplimentara",
      "calculator-leasing-vs-credit",
    ],
    coreArticles: [
      "cum-citesti-costul-total-al-unui-credit",
      "cum-afli-ce-rata-iti-permiti-fara-sa-iti-blochezi-bugetul",
      "cand-merita-refinantarea-si-cand-doar-pare-o-idee-buna",
      "cum-iti-construiesti-fondul-de-urgenta-fara-sa-ramai-fara-lichiditati",
      "cum-planifici-economii-pe-termen-lung-pentru-obiective-mari",
      "leasing-vs-credit-cum-compari-corect-doua-scenarii-de-finantare",
    ],
    supportPages: [
      "/calculatoare/credite-si-economii",
      "/pentru-persoane",
      "/blog/cum-citesti-costul-total-al-unui-credit",
    ],
  },
  {
    slug: "energie-pentru-casa",
    label: "Energie pentru casa",
    audience: "consumer",
    businessGoal: "Construim clusterul cu cea mai buna combinatie intre intentie informationala, comparatii de achizitie si monetizare prin echipamente.",
    primaryIntent: [
      "factura curent",
      "consum aparat",
      "panouri fotovoltaice",
      "amortizare fotovoltaice",
      "dimensionare climatizare/incalzire",
    ],
    priorityQuestions: [
      "Cat ma costa realist consumul de curent al casei?",
      "Cate panouri imi trebuie pentru consumul actual?",
      "In cat timp se amortizeaza investitia in fotovoltaice?",
      "Ce putere de racire sau incalzire are sens pentru locuinta mea?",
    ],
    commercialAngles: [
      "Factura curenta versus economie potentiala",
      "Investitie in panouri versus amortizare prudenta",
      "Alegerea echipamentului dupa cost anual, nu doar dupa putere",
    ],
    hubPaths: ["/calculatoare/energie-pentru-casa", "/pentru-persoane"],
    linkingRules: [
      "Articolele de explicare a facturii trebuie sa trimita catre factura, consum aparat si productie fotovoltaica.",
      "Calculatoarele fotovoltaice trebuie legate intre ele in ordinea consum -> sistem -> productie -> amortizare.",
      "Hub-ul trebuie sa separe clar zona de cost, zona de productie si zona de alegere echipament.",
    ],
    coreCalculators: [
      "calculator-factura-curent",
      "calculator-consum-aparat-electric",
      "calculator-necesar-sistem-fotovoltaic",
      "calculator-amortizare-panouri-fotovoltaice",
      "calculator-numar-panouri-fotovoltaice",
      "calculator-productie-fotovoltaica",
      "calculator-dimensiune-baterie-fotovoltaice",
      "calculator-necesar-incalzire",
      "calculator-dimensiune-pompa-de-caldura",
      "calculator-btu-aer-conditionat",
    ],
    coreArticles: [
      "cum-citesti-factura-de-curent-fara-sa-te-pierzi-in-detalii-inutile",
      "cum-citesti-amortizarea-unui-sistem-fotovoltaic",
      "cate-panouri-fotovoltaice-iti-trebuie-de-fapt",
      "cum-estimezi-productia-fotovoltaica-fara-promisiuni-umflate",
      "centrala-vs-pompa-de-caldura-cum-compari-corect-costurile",
    ],
    supportPages: [
      "/calculatoare/energie-pentru-casa",
      "/pentru-persoane",
      "/blog/cum-citesti-factura-de-curent-fara-sa-te-pierzi-in-detalii-inutile",
    ],
  },
  {
    slug: "imobiliare",
    label: "Imobiliare",
    audience: "consumer",
    businessGoal: "Facem hub-ul de decizie imobiliara util atat pentru locuire, cat si pentru investitii mici, cu pagini care pot monetiza prin lead-uri si comparatii.",
    primaryIntent: [
      "cost total achizitie locuinta",
      "pret pe mp",
      "chirie versus cumparare",
      "randament din chirie",
      "costuri recurente proprietate",
    ],
    priorityQuestions: [
      "Cat ma costa cu adevarat achizitia, nu doar pretul de lista?",
      "Merita chirie sau cumparare in scenariul meu actual?",
      "Ce randament ramane dupa costurile reale?",
      "Cat de sensibila este investitia la neocupare si renovare?",
    ],
    commercialAngles: [
      "Pret pe mp versus cost total de intrare",
      "Locuire proprie versus investitie mica",
      "Randament brut versus randament ramas dupa costuri",
    ],
    hubPaths: ["/calculatoare/imobiliare", "/pentru-persoane"],
    linkingRules: [
      "Pagina de cost total trebuie sa trimita spre pret pe mp si buget lunar.",
      "Zona de investitie trebuie legata prin randament, neocupare, costuri recurente si administrare.",
      "Articolele chirie versus cumparare trebuie sa trimita spre doua calculatoare complementare, nu doar unul.",
    ],
    coreCalculators: [
      "calculator-cost-total-achizitie-locuinta",
      "calculator-pret-pe-mp",
      "calculator-chirie-vs-cumparare",
      "calculator-buget-lunar-locuinta",
      "calculator-randament-chirie",
      "calculator-pierdere-din-neocupare",
      "calculator-buget-renovare",
      "calculator-avans-proprietate",
      "calculator-costuri-recurente-proprietate",
      "calculator-cost-administrare-proprietate",
    ],
    coreArticles: [
      "ce-intra-de-fapt-in-bugetul-total-de-achizitie-al-unei-locuinte",
      "chirie-vs-cumparare-cum-compari-corect-doua-scenarii",
      "cum-citesti-randamentul-din-chirie-fara-sa-ignori-costurile-ascunse",
      "cum-estimezi-un-buget-de-renovare-fara-optimism-periculos",
      "cat-te-costa-administrarea-unei-proprietati-inchiriate",
    ],
    supportPages: [
      "/calculatoare/imobiliare",
      "/pentru-persoane",
      "/blog/ce-intra-de-fapt-in-bugetul-total-de-achizitie-al-unei-locuinte",
    ],
  },
];

export const SPRINT_B_30_PAGE_ROADMAP: SprintBRoadmapPage[] = [
  {
    cluster: "credite-si-economii",
    kind: "hub",
    slug: "credite-si-economii",
    title: "Hub credite si economii",
    priorityTier: "tier-1",
    intent: "Hub principal pentru intentie financiara mare",
    reason: "Leaga cele mai bune pagini de credit, refinantare si economisire intr-o navigare clara.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-cost-total-credit",
    title: "Calculator cost total credit",
    priorityTier: "tier-1",
    intent: "Answer-first pentru cost total",
    reason: "E una dintre cele mai puternice pagini pentru decizie si monetizare.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-rata-maxima-suportabila",
    title: "Calculator rata maxima suportabila",
    priorityTier: "tier-1",
    intent: "Buget lunar si stres financiar",
    reason: "Completeaza costul total si face clusterul mult mai actionabil.",
  },
  {
    cluster: "credite-si-economii",
    kind: "article",
    slug: "cum-citesti-costul-total-al-unui-credit",
    title: "Cum citesti costul total al unui credit",
    priorityTier: "tier-1",
    intent: "Explicare si AEO",
    reason: "Ridica increderea si sustine calculatorul principal.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-economie-refinantare",
    title: "Calculator economie refinantare",
    priorityTier: "tier-1",
    intent: "Comparatie de scenarii",
    reason: "Are intentie comerciala buna si leaga organic de oferte.",
  },
  {
    cluster: "credite-si-economii",
    kind: "article",
    slug: "cand-merita-refinantarea-si-cand-doar-pare-o-idee-buna",
    title: "Cand merita refinantarea",
    priorityTier: "tier-1",
    intent: "Decizie prudenta",
    reason: "Reduce riscul de continut generic si creste E-E-A-T.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-grad-de-indatorare",
    title: "Calculator grad de indatorare",
    priorityTier: "tier-2",
    intent: "Filtru de eligibilitate",
    reason: "Completeaza foarte bine rata maxima suportabila.",
  },
  {
    cluster: "credite-si-economii",
    kind: "calculator",
    slug: "calculator-fond-de-urgenta",
    title: "Calculator fond de urgenta",
    priorityTier: "tier-2",
    intent: "Obiectiv de economisire",
    reason: "Deschide clusterul spre disciplinarea financiara si CTA-uri soft.",
  },
  {
    cluster: "credite-si-economii",
    kind: "article",
    slug: "cum-iti-construiesti-fondul-de-urgenta-fara-sa-ramai-fara-lichiditati",
    title: "Cum iti construiesti fondul de urgenta",
    priorityTier: "tier-2",
    intent: "Educatie financiara aplicata",
    reason: "Leaga creditele de lichiditate si buffer personal.",
  },
  {
    cluster: "credite-si-economii",
    kind: "article",
    slug: "cum-planifici-economii-pe-termen-lung-pentru-obiective-mari",
    title: "Cum planifici economii pe termen lung",
    priorityTier: "tier-3",
    intent: "Suport pentru economisire",
    reason: "Consolideaza clusterul si deschide subtopicuri noi.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "hub",
    slug: "energie-pentru-casa",
    title: "Hub energie pentru casa",
    priorityTier: "tier-1",
    intent: "Hub principal pentru cost si echipamente",
    reason: "Este poarta de intrare pentru un cluster foarte bun de trafic si monetizare.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-factura-curent",
    title: "Calculator factura curent",
    priorityTier: "tier-1",
    intent: "Cost lunar realist",
    reason: "Are intentie simpla, volum bun si onboarding clar in cluster.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "article",
    slug: "cum-citesti-factura-de-curent-fara-sa-te-pierzi-in-detalii-inutile",
    title: "Cum citesti factura de curent",
    priorityTier: "tier-1",
    intent: "Interpretare answer-first",
    reason: "Creste increderea si reduce abandonul dupa prima cifra.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-consum-aparat-electric",
    title: "Calculator consum aparat electric",
    priorityTier: "tier-1",
    intent: "Cost punctual pe aparat",
    reason: "Este cea mai buna punte intre interes vag si decizie practica.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-necesar-sistem-fotovoltaic",
    title: "Calculator necesar sistem fotovoltaic",
    priorityTier: "tier-1",
    intent: "Dimensionare investitie",
    reason: "Deschide tot clusterul fotovoltaic si comparatiile comerciale.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-amortizare-panouri-fotovoltaice",
    title: "Calculator amortizare panouri fotovoltaice",
    priorityTier: "tier-1",
    intent: "Payback si decizie financiara",
    reason: "Leaga costul energiei de decizia de investitie.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "article",
    slug: "cum-citesti-amortizarea-unui-sistem-fotovoltaic",
    title: "Cum citesti amortizarea unui sistem fotovoltaic",
    priorityTier: "tier-1",
    intent: "Explicare si comparatie",
    reason: "Previne concluziile naive si sustine monetizarea prudenta.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "article",
    slug: "cate-panouri-fotovoltaice-iti-trebuie-de-fapt",
    title: "Cate panouri fotovoltaice iti trebuie",
    priorityTier: "tier-2",
    intent: "Sizing answer-first",
    reason: "Consolideaza traseul consum -> sistem -> amortizare.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "calculator",
    slug: "calculator-productie-fotovoltaica",
    title: "Calculator productie fotovoltaica",
    priorityTier: "tier-2",
    intent: "Validare productie",
    reason: "Ajuta mult la interpretarea amortizarii si a numarului de panouri.",
  },
  {
    cluster: "energie-pentru-casa",
    kind: "article",
    slug: "centrala-vs-pompa-de-caldura-cum-compari-corect-costurile",
    title: "Centrala vs pompa de caldura",
    priorityTier: "tier-3",
    intent: "Comparatie comerciala",
    reason: "Deschide verticala de echipamente si oferte.",
  },
  {
    cluster: "imobiliare",
    kind: "hub",
    slug: "imobiliare",
    title: "Hub imobiliare",
    priorityTier: "tier-1",
    intent: "Hub pentru locuire si investitii mici",
    reason: "Poate deveni una dintre cele mai valoroase pagini de cluster.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-cost-total-achizitie-locuinta",
    title: "Calculator cost total achizitie locuinta",
    priorityTier: "tier-1",
    intent: "Cost complet de intrare",
    reason: "Este cea mai importanta pagina de decizie pentru acest cluster.",
  },
  {
    cluster: "imobiliare",
    kind: "article",
    slug: "ce-intra-de-fapt-in-bugetul-total-de-achizitie-al-unei-locuinte",
    title: "Ce intra in bugetul total de achizitie",
    priorityTier: "tier-1",
    intent: "Interpretare si education",
    reason: "Sustine direct calculatorul principal si creste increderea.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-pret-pe-mp",
    title: "Calculator pret pe mp",
    priorityTier: "tier-1",
    intent: "Comparatie rapida intre oferte",
    reason: "E foarte bun pentru trafic si pentru intrarea in cluster.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-chirie-vs-cumparare",
    title: "Calculator chirie vs cumparare",
    priorityTier: "tier-1",
    intent: "Comparatie de scenarii",
    reason: "Are intentie mare si valoare foarte buna pentru sharing.",
  },
  {
    cluster: "imobiliare",
    kind: "article",
    slug: "chirie-vs-cumparare-cum-compari-corect-doua-scenarii",
    title: "Chirie vs cumparare",
    priorityTier: "tier-1",
    intent: "Comparatie answer-first",
    reason: "Poate lua snippet-uri si sustine calculatorul principal.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-randament-chirie",
    title: "Calculator randament chirie",
    priorityTier: "tier-2",
    intent: "Investitie imobiliara mica",
    reason: "Deschide foarte bine subclusterul de randament.",
  },
  {
    cluster: "imobiliare",
    kind: "article",
    slug: "cum-citesti-randamentul-din-chirie-fara-sa-ignori-costurile-ascunse",
    title: "Cum citesti randamentul din chirie",
    priorityTier: "tier-2",
    intent: "Interpretare randament",
    reason: "Previne concluzii gresite si creste E-E-A-T.",
  },
  {
    cluster: "imobiliare",
    kind: "calculator",
    slug: "calculator-buget-renovare",
    title: "Calculator buget renovare",
    priorityTier: "tier-2",
    intent: "Cost de adaptare sau investitie",
    reason: "Face clusterul mai complet pentru achizitie si investitie.",
  },
  {
    cluster: "imobiliare",
    kind: "article",
    slug: "cum-estimezi-un-buget-de-renovare-fara-optimism-periculos",
    title: "Cum estimezi un buget de renovare",
    priorityTier: "tier-3",
    intent: "Suport pentru decizie",
    reason: "Leaga costurile initiale de scenariile reale.",
  },
];

export const SPRINT_B_GLOBAL_GAPS = [
  {
    slug: "zile-libere-2026",
    title: "Zile libere 2026",
    kind: "article" as const,
    reason: "Este singurul content gap real repetat in 404-uri si poate aduce trafic sezonier rapid.",
  },
];

export const getSprintBCluster = (slug: string) =>
  SPRINT_B_CLUSTERS.find((cluster) => cluster.slug === slug);
